<?php 

$mailBody = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="Content-Language" content="en" />
		<title>L.R.P.D. Announcement</title>
		<style type="text/css">
		
			body
			{
				background-color: #1b1c1f;
				color: #9d9ea2;
				font-family: Georgia, Times New Roman, serif;
				font-style: italic;
				font-weight: lighter;
				font-size: 16px;
				line-height: 20px;
				margin: 0px;
				padding: 0px;
			}
			img
			{
				margin: 0px;
				padding: 0px;
				border: none;
			}
			img.repeater
			{
				margin: 0px 0px 3px 0px;
			}
			hr
			{
				margin: 30px 0px 25px 0px;
				padding: 0px;
				width: 100%;
				border: 0px none;
				border-bottom: 1px;
				border-bottom-style: dotted;
				border-bottom-color: #4a4743;
			}
			h1, h1 a
			{
				color: #9d9ea2;
				font-family: Georgia, Times New Roman, serif;
				font-style: normal;
				font-weight: lighter;
				font-size: 28px;
				line-height: 36px;
				margin: 0px 0px 16px 0px;
				padding: 0px;
			}
			a
			{
				color: #ff9c00;
			}
			a:link, div.text a:link, div.meta a:link, h1 a:link, h2 a:link, h3 a:link
			{
				text-decoration: none;
			}
			a:visited, div.text a:visited, div.meta a:visited, h1 a:visited, h2 a:visited, h3 a:visited
			{
				text-decoration: none;
			}
			a:hover, div.text a:hover, div.meta a:hover, h1 a:hover, h2 a:hover, h3 a:hover
			{
				text-decoration: underline;
			}
			a:active, div.text a:active, div.meta a:active, h1 a:active, h2 a:active, h3 a:active
			{
				text-decoration: underline;
			}
		
		</style>
	<meta name="robots" content="noindex,nofollow"></meta>
<meta property="og:title" content="Graffiti S.W.A.T."></meta>
</head>
	<body bgcolor="#1b1c1f" text="#9d9ea2" link="#ff9c00" vlink="#ff9c00" alink="#ff9c00" marginheight="0" marginwidth="0" topmargin="0" leftmargin="0" style="background-color:#1b1c1f;color:#9d9ea2;font-family:Georgia, Times New Roman, serif;font-style:italic;font-weight:lighter;font-size:16px;line-height:18px;margin-top:0px;margin-bottom:0px;margin-right:0px;margin-left:0px;padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;" >
		<table width="100%" border="0" cellspacing="0" cellpadding="0" >
			<tr>
				<td></td>
				<td align="center">
					<table width="850" border="0" cellspacing="0" cellpadding="0">
						<tr>
							<td align="left" valign="top">
								<center>
									<div style="margin-top:5px;color:#9d9ea2;font-family:Georgia, Times New Roman, serif;font-style:italic;font-weight:lighter;font-size:12px;line-height:12px;margin-bottom:0px;margin-right:0px;margin-left:0px;padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;" >If you can&#39;t read this e-mail, <a href="http://www.mee-mail.com/graffitiswat/newsletter/01.html" style="color:#ff9c00;text-decoration:none;" >click here</a> to see it in your browser.</div></td>
								</center>
						</tr>
						<tr>
							<td align="left" valign="top">
								<a href="http://www.facebook.com/GraffitiSWAT">
									<img src="http://www.mee-mail.com/graffitiswat/newsletter/images/top.jpg" alt="Graffiti S.W.A.T." border="0" width="850" height="315" style="border:none;margin-top:7px;margin-bottom:50px;margin-right:0px;margin-left:0px;padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;border-style:none;" /></a></td>
						</tr>
					</table>
					
					<table width="850" border="0" cellspacing="0" cellpadding="0">
						<tr>
							<td><div style="width:100px;"></div></td>
							<td align="left" valign="top">
								<div style="width:425px; margin-top:0px;color:#9d9ea2;font-family:Georgia, Times New Roman, serif;font-style:italic;font-weight:lighter;font-size:16px;line-height:18px;margin-bottom:16px;margin-right:0px;margin-left:0px;padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;" >
									<p style="color:#9d9ea2;font-family:Georgia, Times New Roman, serif;font-style:italic;font-weight:lighter;font-size:16px;line-height:20px;margin-top:0px;margin-bottom:16px;margin-right:0px;margin-left:0px;padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;" >
										Hello vandals,<br /><br />
										
										it&#39;s been a while since the last update on VandalSquad, but we hope it was worth the wait.<br />
										We have launched a brand new graffiti application!<br /><br />
										
										It&#39;s called Graffiti S.W.A.T. and you can try it out here:<br />
										<a href="http://www.facebook.com/GraffitiSWAT" class="bg" style="text-decoration:none;color:#ff9c00;font-family:Georgia, Times New Roman, serif;font-style:italic;font-weight:lighter;font-size:16px;line-height:18px;padding-top:2px;padding-bottom:0px;padding-right:0px;padding-left:0px;margin-right:0px;" >http://www.facebook.com/GraffitiSWAT</a><br/><br />
										
										We have built it as a Facebook app to reduce spam and the hacking of profiles. It&#39;s also built in Flash, meaning it&#39;ll run on Mac OSX too.<br /><br />
	
										Plenty of new features are planned, including:<br /><br />
										
										<ul>
											<li>Graffi-Tee: Spray your own t-shirt and get it printed</li><br />
											<li>3D graffiti: Spray on real 3D walls and trains</li><br />
											<li>S.W.A.T.-Shop: Download new surfaces,  or upload and , share your own self-made backgrounds.</li><br /><br />
										</ul>
										
										This and more coming soon.<br />
										Go have a look!<br /><br />
										
										Yours,<br />
										the friendly officers from the L.R.P.D.<br /><br /><br /><br />
										
										<a href="http://www.facebook.com/GraffitiSWAT" class="bg" style="text-decoration:none;color:#ff9c00;font-family:Georgia, Times New Roman, serif;font-style:italic;font-weight:lighter;font-size:16px;line-height:18px;padding-top:2px;padding-bottom:0px;padding-right:0px;padding-left:0px;margin-right:0px;" >Like us on Facebook</a> to stay in touch about latest developments
									</p>
								</div></td>
							<td><div style="width:67px;"></div></td>
							<td align="left" valign="top"><div style="width:258px;">
								<img src="http://www.mee-mail.com/graffitiswat/newsletter/images/pictures_258px.jpg" alt="Graffiti S.W.A.T." width="258" height="820" style="margin-top:0px;margin-bottom:50px;margin-right:0px;margin-left:0px;padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;border-style:none;" /></div></td>
						</tr>
					</table>
					</table>
				</td>
			</tr>
		</table>
	</body>
</html>';


?>