		
			<div class="header">

				<div class="navigation">
					<div class="top_mail">
						<div class="top_mail_content">
	
							<ul>
								<li>
									<a href="index.php">
									</a>
								</li>
								<li>
									<a class="mails" href="http://www.facebook.com/GraffitiSWAT" title="Wall" target="_top">
										Facebook Wall
									</a>
								</li>
								<li>
									<a href="http://www.facebook.com/GraffitiSWAT?sk=photos" title="Gallery" target="_top">
										S.W.A.T. Gallery
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>

			</div>
	<div style="clear: both;"></div>
	<div class="line_seperator"></div>
